export const ROUTES = {
  home: "/",
  mentorHome: "/mentorHome",
  matching: "/matching",
  jobDetail: "/jobs/haenyeo",
  matchingDetail: "/matching/detail",
  experienceDetail: "/experiences/haenyeo",
  reservation: "/reservation",
  onboarding: "/onboarding",
  register: "/register",
  login: "/login",
  my: "/my",
  mentorMy: "/mentorMy",
  components: "/components",
  mentorPreview: "/mentors/stone-master",
  tokens: "/tokens",
} as const;
